Update docs for HTTP feature
moovweb-docs/xdn-docs pull request #71
Opened 2020-10-02 02:15 UTC by ierceg

2020-10-02 02:15 UTC, ianand commented
Task linked: [XDN-5710 Update docs](https://app.clickup.com/t/4205457/XDN-5710)

2020-10-02 09:48 UTC, markbrocato commented on guides/security.md
> +The Moovweb XDN by default only serves the traffic over `https` protocol. It automatically redirects `http` requests to the same URL, including any query strings, on `https`.
```suggestion
By default the Moovweb XDN only serves traffic over the `https` protocol. It automatically redirects `http` requests to the same URL, including any query strings, on `https`.
```

2020-10-02 09:49 UTC, markbrocato commented on guides/security.md
> +We strongly discourage the use of `http` protocol but if you *must* enable it then you can explicitly match on `http` protocol. For example:
```suggestion
We strongly discourage the use of `http` protocol but if you *must* enable it then you can do so by adding `protocol: 'http'` to your route criteria. For example:
```

2020-10-02 09:50 UTC, markbrocato commented on guides/security.md
> +If no route is matched on `http` protocol then the XDN will fallback on its default behavior of automatically redirecting the traffic to `https`.
```suggestion
If no route is matched on `http` protocol then the XDN will fallback on its default behavior of automatically redirecting the request to `https`.
```

2020-10-02 09:54 UTC, markbrocato commented on guides/security.md
> +* The received protocol can be read from [`x-xdn-protocol`](request_headers#section_general_headers) request header or from [`req.secure`](/docs/api/core/interfaces/_router_request_.request.html#secu
```suggestion
* A request's protocol can be determined by reading the [`x-xdn-protocol`](request_headers#section_general_headers) request header or the [`request.secure`](/docs/api/core/interfaces/_router_request_.request.html#secure) property.
```

2020-10-02 09:56 UTC, markbrocato commented on guides/security.md
> +* Running in local development assumes that you are developing on `https` protocol. When you want to test your router for `http` protocol matching you should either set `xdn_emulate_local_http` cooki
```suggestion
* During local development all requests will appear secure by default.  To test your router for `http` protocol matching you must either set the `xdn_emulate_local_http` cookie to `true` (if using a browser) or send an `x-xdn-protocol` request header set to `http`.
```

2020-10-02 09:56 UTC, markbrocato requested changes
See my suggestions.

2020-10-07 11:37 UTC, markbrocato approved these changes

2020-10-07 12:06 UTC, merged